#!/usr/bin/env bash
#
# ============================================================
#        APPLE II Emulator for ESP32-TTGO-VGA
#   (C) 2026 Reinaldo Torres / CoCo Byte Club
#   https://github.com/reyco2000/ESP32-TTGO-VGA_AppleII_Emulator
#   MIT License
# ============================================================
#  File   : run-layout-tests.sh
#  Module : Builds the host-side keyboard layout test
#           (tests/host/layout_test.cpp plus the real
#           src/Tools/KeyboardLayouts.cpp) and runs it against
#           FabGL's own layout data and ASCII conversion.
# ============================================================
#
# Usage:  tests/host/run-layout-tests.sh
#
# FabGL's kbdlayouts.cpp and codepages.cpp are plain tables and compile on
# the host, but the fabutils.h they include is ESP32-only. The VirtualKey
# enum, VirtualKeyItem and the ASCII constants are extracted from the
# installed copy into a generated stand-in, so the test always runs against
# the same definitions the firmware is built with.
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
BUILD="$HERE/build"
GEN="$BUILD/gen"

FABGL="${FABGL_DIR:-$HOME/Arduino/libraries/FabGL}"
[ -d "$FABGL/src" ] || { echo "error: FabGL not found at $FABGL (set FABGL_DIR)"; exit 1; }

mkdir -p "$GEN"

# the stand-in has to shadow the real fabutils.h, so $GEN comes first on the
# include path; kbdlayouts.h and codepages.h themselves are the real ones
{
  echo '// generated by run-layout-tests.sh from FabGL fabutils.h - do not edit'
  echo '#pragma once'
  echo '#include <stdint.h>'
  echo '#include <stddef.h>'
  echo 'namespace fabgl {'
  awk '/^enum VirtualKey \{/,/^#define ASCII_DEL/' "$FABGL/src/fabutils.h"
  echo '}'
} > "$GEN/fabutils.h"

grep -q 'struct VirtualKeyItem' "$GEN/fabutils.h" || { echo "error: could not extract VirtualKey enum from FabGL"; exit 1; }

# A quoted include is resolved against the including file's own directory
# first, so FabGL's sources would find the real fabutils.h next to them
# whatever the include path says. Copy them in beside the stand-in instead.
cp "$FABGL/src/codepages.h" "$FABGL/src/codepages.cpp" \
   "$FABGL/src/devdrivers/kbdlayouts.h" "$FABGL/src/devdrivers/kbdlayouts.cpp" "$GEN/"

echo "==> Building layout_test"
g++ -std=gnu++17 -O1 -Wall -Wno-unused-variable \
  -I "$GEN" -I "$HERE/shim" -I "$ROOT/src/Tools" \
  -o "$BUILD/layout_test" \
  "$HERE/layout_test.cpp" "$ROOT/src/Tools/KeyboardLayouts.cpp" \
  "$GEN/kbdlayouts.cpp" "$GEN/codepages.cpp"

"$BUILD/layout_test"
