/*
 * ============================================================
 *        APPLE II Emulator for ESP32-TTGO-VGA
 *   (C) 2026 Reinaldo Torres / CoCo Byte Club
 *   https://github.com/reyco2000/ESP32-TTGO-VGA_AppleII_Emulator
 *   Based on codesafe/ESP32-VGA_AppleII_Emulator , co-developed with Claude Code
 *   MIT License
 * ============================================================
 *  File   : KeyboardLayouts.cpp
 *  Module : The layout tables themselves. Key positions come from the
 *           X11 xkb data (symbols/latam and symbols/br, both built on
 *           symbols/latin), translated into the PS/2 scancodes FabGL's
 *           USLayout uses for the same physical keys.
 *
 *           Two deliberate departures from a PC keyboard, because the
 *           Apple II cannot compose accents:
 *             - a key whose only job is an accent that also exists in
 *               ASCII (~ ^ ` ') types that character outright instead
 *               of waiting for a vowel
 *             - the acute and diaeresis keys stay dead keys, and the
 *               accented letters they make are then dropped, since the
 *               Apple has no glyph for them
 * ============================================================
*/

#include "KeyboardLayouts.h"

using namespace fabgl;

//////////////////////////////////////////////////////////////////////////////// Spanish (Latin American)
//
//  xkb: latam, which is latin(type4) plus its own overrides.
//
//    key left of 1   | °        AE07  7 /      AC10  N-tilde
//    AE01  1 ! |       AE08  8 ( [      AC11  { [ ^
//    AE02  2 " @       AE09  9 ) ]      BKSL  } ] `
//    AE03  3 # .       AE10  0 = }      AB08  , ;
//    AE04  4 $ ~       AE11  ' ? \      AB09  . :
//    AE06  6 & ~(not)  AE12  inverted ? !   AB10  - _
//    AD11  dead acute / diaeresis        AD12  + * ~
//    LSGT (right of left Shift)  < > \
//
const KeyboardLayout LatinAmericanLayout {
	// name
	"LA",

	// desc
	"Latin American",

	// inherited layout: letters, digits and the keys that do not move
	&USLayout,

	// single byte scancodes
	{
		{ 0x0E, VK_VERTICALBAR },    // left of 1:  |  °  ¬
		{ 0x4A, VK_MINUS },          // -  _
		{ 0x4C, VK_TILDE_n },        // right of L: ñ  Ñ  ~
		{ 0x4E, VK_QUOTE },          // '  ?  backslash
		{ 0x52, VK_LEFTBRACE },      // {  [  ^
		{ 0x54, VK_ACUTEACCENT },    // dead acute / dead diaeresis
		{ 0x55, VK_QUESTION_INV },   // inverted ?  inverted !
		{ 0x5B, VK_PLUS },           // +  *  ~
		{ 0x5D, VK_RIGHTBRACE },     // left of Enter:  }  ]  `
		{ 0x61, VK_LESS },           // right of left Shift:  <  >  backslash
	},

	// extended scancodes (0xE0..)
	{
	},

	// virtual keys generated by other virtual keys combinations
	//  in_key, { CTRL, LALT, RALT, SHIFT }, out_key
	{
		{ VK_1,            { 0, 0, 1, 0 }, VK_VERTICALBAR },   // ALTGR "1" = "|"

		{ VK_2,            { 0, 0, 0, 1 }, VK_QUOTEDBL },      // SHIFT "2" = '"'
		{ VK_2,            { 0, 0, 1, 0 }, VK_AT },            // ALTGR "2" = "@"

		{ VK_3,            { 0, 0, 1, 0 }, VK_INTERPUNCT },    // ALTGR "3" = "·"

		{ VK_4,            { 0, 0, 1, 0 }, VK_TILDE },         // ALTGR "4" = "~"

		{ VK_6,            { 0, 0, 0, 1 }, VK_AMPERSAND },     // SHIFT "6" = "&"
		{ VK_6,            { 0, 0, 1, 0 }, VK_NEGATION },      // ALTGR "6" = "¬"

		{ VK_7,            { 0, 0, 0, 1 }, VK_SLASH },         // SHIFT "7" = "/"
		{ VK_7,            { 0, 0, 1, 0 }, VK_LEFTBRACE },     // ALTGR "7" = "{"

		{ VK_8,            { 0, 0, 0, 1 }, VK_LEFTPAREN },     // SHIFT "8" = "("
		{ VK_8,            { 0, 0, 1, 0 }, VK_LEFTBRACKET },   // ALTGR "8" = "["

		{ VK_9,            { 0, 0, 0, 1 }, VK_RIGHTPAREN },    // SHIFT "9" = ")"
		{ VK_9,            { 0, 0, 1, 0 }, VK_RIGHTBRACKET },  // ALTGR "9" = "]"

		{ VK_0,            { 0, 0, 0, 1 }, VK_EQUALS },        // SHIFT "0" = "="
		{ VK_0,            { 0, 0, 1, 0 }, VK_RIGHTBRACE },    // ALTGR "0" = "}"

		{ VK_VERTICALBAR,  { 0, 0, 0, 1 }, VK_DEGREE },        // SHIFT "|" = "°"
		{ VK_VERTICALBAR,  { 0, 0, 1, 0 }, VK_NEGATION },      // ALTGR "|" = "¬"

		{ VK_QUOTE,        { 0, 0, 0, 1 }, VK_QUESTION },      // SHIFT "'" = "?"
		{ VK_QUOTE,        { 0, 0, 1, 0 }, VK_BACKSLASH },     // ALTGR "'" = "\"

		{ VK_QUESTION_INV, { 0, 0, 0, 1 }, VK_EXCLAIM_INV },   // SHIFT "¿" = "¡"

		{ VK_ACUTEACCENT,  { 0, 0, 0, 1 }, VK_DIAERESIS },     // SHIFT acute = diaeresis

		{ VK_PLUS,         { 0, 0, 0, 1 }, VK_ASTERISK },      // SHIFT "+" = "*"
		{ VK_PLUS,         { 0, 0, 1, 0 }, VK_TILDE },         // ALTGR "+" = "~"

		{ VK_TILDE_n,      { 0, 0, 0, 1 }, VK_TILDE_N },       // SHIFT "ñ" = "Ñ"
		{ VK_TILDE_n,      { 0, 0, 1, 0 }, VK_TILDE },         // ALTGR "ñ" = "~"

		{ VK_LEFTBRACE,    { 0, 0, 0, 1 }, VK_LEFTBRACKET },   // SHIFT "{" = "["
		{ VK_LEFTBRACE,    { 0, 0, 1, 0 }, VK_CARET },         // ALTGR "{" = "^"

		{ VK_RIGHTBRACE,   { 0, 0, 0, 1 }, VK_RIGHTBRACKET },  // SHIFT "}" = "]"
		{ VK_RIGHTBRACE,   { 0, 0, 1, 0 }, VK_GRAVEACCENT },   // ALTGR "}" = "`"

		{ VK_LESS,         { 0, 0, 0, 1 }, VK_GREATER },       // SHIFT "<" = ">"
		{ VK_LESS,         { 0, 0, 1, 0 }, VK_BACKSLASH },     // ALTGR "<" = "\"

		{ VK_COMMA,        { 0, 0, 0, 1 }, VK_SEMICOLON },     // SHIFT "," = ";"
		{ VK_PERIOD,       { 0, 0, 0, 1 }, VK_COLON },         // SHIFT "." = ":"
	},

	// dead keys: the accented letters they make have no Apple II glyph and
	// are dropped, but the composition still has to happen or the accent
	// would type as a character of its own
	{
		VK_ACUTEACCENT,
		VK_DIAERESIS,
	},

	// dead key + virtual key = replaced virtual key
	{
		{ VK_ACUTEACCENT, VK_a, VK_ACUTE_a },
		{ VK_ACUTEACCENT, VK_e, VK_ACUTE_e },
		{ VK_ACUTEACCENT, VK_i, VK_ACUTE_i },
		{ VK_ACUTEACCENT, VK_o, VK_ACUTE_o },
		{ VK_ACUTEACCENT, VK_u, VK_ACUTE_u },
		{ VK_ACUTEACCENT, VK_A, VK_ACUTE_A },
		{ VK_ACUTEACCENT, VK_E, VK_ACUTE_E },
		{ VK_ACUTEACCENT, VK_I, VK_ACUTE_I },
		{ VK_ACUTEACCENT, VK_O, VK_ACUTE_O },
		{ VK_ACUTEACCENT, VK_U, VK_ACUTE_U },

		{ VK_DIAERESIS,   VK_a, VK_UMLAUT_a },
		{ VK_DIAERESIS,   VK_e, VK_UMLAUT_e },
		{ VK_DIAERESIS,   VK_i, VK_UMLAUT_i },
		{ VK_DIAERESIS,   VK_o, VK_UMLAUT_o },
		{ VK_DIAERESIS,   VK_u, VK_UMLAUT_u },
		{ VK_DIAERESIS,   VK_A, VK_UMLAUT_A },
		{ VK_DIAERESIS,   VK_E, VK_UMLAUT_E },
		{ VK_DIAERESIS,   VK_I, VK_UMLAUT_I },
		{ VK_DIAERESIS,   VK_O, VK_UMLAUT_O },
		{ VK_DIAERESIS,   VK_U, VK_UMLAUT_U },
	},
};

//////////////////////////////////////////////////////////////////////////////// Portuguese (Brazil), ABNT2
//
//  xkb: br(abnt2), which is latin plus its own overrides.
//
//    key left of 1   ' "      AD12  [ {        AB10  ; :
//    AE02  2 @ (as US)        BKSL  ] }        AB11  / ?   (left of right Shift)
//    AE06  6 diaeresis        AC10  C-cedilla  LSGT  \ |   (right of left Shift)
//    AD11  dead acute / `     AC11  ~ ^
//
//  The number row is the US one, so only the keys above are listed here.
//
const KeyboardLayout BrazilianLayout {
	// name
	"BR",

	// desc
	"Brazilian ABNT2",

	// inherited layout
	&USLayout,

	// single byte scancodes
	{
		{ 0x0E, VK_QUOTE },          // left of 1:  '  "
		{ 0x4A, VK_SEMICOLON },      // ;  :
		{ 0x4C, VK_CEDILLA_c },      // right of L: ç  Ç
		{ 0x51, VK_SLASH },          // left of right Shift:  /  ?
		{ 0x52, VK_TILDE },          // ~  ^
		{ 0x54, VK_ACUTEACCENT },    // dead acute, then "`"
		{ 0x5B, VK_LEFTBRACKET },    // [  {
		{ 0x5D, VK_RIGHTBRACKET },   // left of Enter:  ]  }
		{ 0x61, VK_BACKSLASH },      // right of left Shift:  \  |
	},

	// extended scancodes (0xE0..)
	{
	},

	// virtual keys generated by other virtual keys combinations
	//  in_key, { CTRL, LALT, RALT, SHIFT }, out_key
	{
		{ VK_6,           { 0, 0, 0, 1 }, VK_DIAERESIS },    // SHIFT "6" = diaeresis, not "^"

		{ VK_q,           { 0, 0, 1, 0 }, VK_SLASH },        // ALTGR "q" = "/"
		{ VK_w,           { 0, 0, 1, 0 }, VK_QUESTION },     // ALTGR "w" = "?"

		{ VK_ACUTEACCENT, { 0, 0, 0, 1 }, VK_GRAVEACCENT },  // SHIFT acute = "`"

		{ VK_CEDILLA_c,   { 0, 0, 0, 1 }, VK_CEDILLA_C },    // SHIFT "ç" = "Ç"

		{ VK_TILDE,       { 0, 0, 0, 1 }, VK_CARET },        // SHIFT "~" = "^"
		{ VK_TILDE,       { 0, 0, 1, 0 }, VK_TILDE },        // ALTGR "~" = "~"
	},

	// dead keys
	{
		VK_ACUTEACCENT,
		VK_DIAERESIS,
	},

	// dead key + virtual key = replaced virtual key
	{
		{ VK_ACUTEACCENT, VK_a, VK_ACUTE_a },
		{ VK_ACUTEACCENT, VK_e, VK_ACUTE_e },
		{ VK_ACUTEACCENT, VK_i, VK_ACUTE_i },
		{ VK_ACUTEACCENT, VK_o, VK_ACUTE_o },
		{ VK_ACUTEACCENT, VK_u, VK_ACUTE_u },
		{ VK_ACUTEACCENT, VK_A, VK_ACUTE_A },
		{ VK_ACUTEACCENT, VK_E, VK_ACUTE_E },
		{ VK_ACUTEACCENT, VK_I, VK_ACUTE_I },
		{ VK_ACUTEACCENT, VK_O, VK_ACUTE_O },
		{ VK_ACUTEACCENT, VK_U, VK_ACUTE_U },

		{ VK_DIAERESIS,   VK_a, VK_UMLAUT_a },
		{ VK_DIAERESIS,   VK_e, VK_UMLAUT_e },
		{ VK_DIAERESIS,   VK_i, VK_UMLAUT_i },
		{ VK_DIAERESIS,   VK_o, VK_UMLAUT_o },
		{ VK_DIAERESIS,   VK_u, VK_UMLAUT_u },
		{ VK_DIAERESIS,   VK_A, VK_UMLAUT_A },
		{ VK_DIAERESIS,   VK_E, VK_UMLAUT_E },
		{ VK_DIAERESIS,   VK_I, VK_UMLAUT_I },
		{ VK_DIAERESIS,   VK_O, VK_UMLAUT_O },
		{ VK_DIAERESIS,   VK_U, VK_UMLAUT_U },
	},
};

//////////////////////////////////////////////////////////////////////////////// the pickable list

static const KeyboardLayoutProfile profiles[KEYBOARD_LAYOUT_COUNT] = {
	{ KEYBOARD_LAYOUT_US,    "US",              &USLayout              },
	{ KEYBOARD_LAYOUT_LATAM, "LATIN AMERICAN",  &LatinAmericanLayout   },
	{ KEYBOARD_LAYOUT_ABNT2, "BRAZILIAN ABNT2", &BrazilianLayout       },
};

const KeyboardLayoutProfile* GetKeyboardLayoutProfile(uint8_t id)
{
	if (id >= KEYBOARD_LAYOUT_COUNT)
		return &profiles[KEYBOARD_LAYOUT_US];
	return &profiles[id];
}

// FabGL starts on the US layout, and so does this, until setup() applies
// whatever was saved in NVS.
static uint8_t currentLayoutId = KEYBOARD_LAYOUT_US;

uint8_t CurrentKeyboardLayoutId()
{
	return currentLayoutId;
}

void SetCurrentKeyboardLayoutId(uint8_t id)
{
	currentLayoutId = GetKeyboardLayoutProfile(id)->id;
}
